### ISSUE TITLE
貌似只有click点击事件触发，没有touch拖动事件？

### ISSUE THREAD

**Issue by JKingdom** [zcweng/ToggleButton#10]
谢谢大大写了这个toggleButton效果
不过貌似这个click只有点击它自己滑动，没有按上去拖动滑动的
扫了下源码貌似是用了spring框架的东西· 不知道这是什么
所以自己不好扩展成touch拖动滑动的样子
希望扩展下
谢谢

还有就是貌似颜色初始化有点问题？

**Comment by zcweng** [comment]
恩，确实只实现了点击切换，效果上用了facebook的开源工具rebound-https://github.com/facebook/rebound
