### ISSUE TITLE
borderWidth属性与com.android.support.design定义的属性冲突

### ISSUE THREAD

**Issue by msdx** [zcweng/ToggleButton#14]
能不能把这个属性改一下名字啊，因为它与android官方的另一个库的属性名冲突了。
另外Android建议第三方库在定义属性时，加一个前缀，希望你可以考虑一下。不然我就不能把它和另一个很酷炫的效果一起合用了。

**Comment by zcweng** [comment]
好的，很好的建议。谢谢
