### ISSUE TITLE
ToggleButton的build.gradle使用com.facebook.rebound:rebound:0.3.+问题

### ISSUE THREAD

**Issue by suncunhu** [zcweng/ToggleButton#17]
Android studio报错
Error:Execution failed for task ':ToggleButtonSample:dexDebug'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/jdk1.8.0_31/bin/java'' finished with non-zero exit value 2

搜索到http://stackoverflow.com/questions/29028705/java-exe-finished-with-non-zero-exit-value-2-when-using-facebook-sdk

修改ToggleButton的build.gradle，注释原来的compile
dependencies {
　//    compile 'com.facebook.rebound:rebound:0.3.+'
   //add 
        compile ('com.facebook.android:facebook-android-sdk:4.1.1'){
        exclude  group:'com.google.android', module: 'support-v4'
        }
}
然后
Android studio提示还需要修改minSdkVersion 8
把两个build.gradle的minSdkVersion 改为14

**Comment by Lee-swifter** [comment]
能有效解决问题，感谢楼主。
